In [2]:
import pandas as pd
import json
import pyarrow as pa
import pyarrow.parquet as pq
import requests

In [7]:
url = ("https://raw.githubusercontent.com/mhollingshead/billboard-hot-100/main/recent.json")
query_parameters = {"downloadformat": "csv"}
response = requests.get(url, params=query_parameters)

In [9]:
response.content

b'{"date":"2025-12-13","data":[{"song":"All I Want For Christmas Is You","artist":"Mariah Carey","this_week":1,"last_week":5,"peak_position":1,"weeks_on_chart":76},{"song":"Last Christmas","artist":"Wham!","this_week":2,"last_week":6,"peak_position":2,"weeks_on_chart":50},{"song":"Rockin\' Around The Christmas Tree","artist":"Brenda Lee","this_week":3,"last_week":7,"peak_position":1,"weeks_on_chart":68},{"song":"Jingle Bell Rock","artist":"Bobby Helms","this_week":4,"last_week":8,"peak_position":3,"weeks_on_chart":65},{"song":"Golden","artist":"HUNTR/X: EJAE, Audrey Nuna & REI AMI","this_week":5,"last_week":2,"peak_position":1,"weeks_on_chart":24},{"song":"The Fate Of Ophelia","artist":"Taylor Swift","this_week":6,"last_week":1,"peak_position":1,"weeks_on_chart":9},{"song":"Ordinary","artist":"Alex Warren","this_week":7,"last_week":3,"peak_position":1,"weeks_on_chart":43},{"song":"Santa Tell Me","artist":"Ariana Grande","this_week":8,"last_week":13,"peak_position":5,"weeks_on_chart":33},{"song":"The Christmas Song (Merry Christmas To You)","artist":"Nat \\"King\\" Cole","this_week":9,"last_week":18,"peak_position":9,"weeks_on_chart":53},{"song":"It\'s The Most Wonderful Time Of The Year","artist":"Andy Williams","this_week":10,"last_week":17,"peak_position":5,"weeks_on_chart":49},{"song":"Underneath The Tree","artist":"Kelly Clarkson","this_week":11,"last_week":19,"peak_position":9,"weeks_on_chart":36},{"song":"Man I Need","artist":"Olivia Dean","this_week":12,"last_week":4,"peak_position":4,"weeks_on_chart":15},{"song":"Let It Snow! Let It Snow! Let It Snow!","artist":"Dean Martin","this_week":13,"last_week":22,"peak_position":7,"weeks_on_chart":39},{"song":"It\'s Beginning To Look A Lot Like Christmas","artist":"Michael Buble","this_week":14,"last_week":21,"peak_position":12,"weeks_on_chart":28},{"song":"Sleigh Ride","artist":"The Ronettes","this_week":15,"last_week":20,"peak_position":8,"weeks_on_chart":36},{"song":"A Holly Jolly Christmas","artist":"Burl Ives","this_week":16,"last_week":24,"peak_position":4,"weeks_on_chart":48},{"song":"Feliz Navidad","artist":"Jose Feliciano","this_week":17,"last_week":23,"peak_position":6,"weeks_on_chart":40},{"song":"Christmas (Baby Please Come Home)","artist":"Darlene Love","this_week":18,"last_week":25,"peak_position":15,"weeks_on_chart":29},{"song":"White Christmas (1947)","artist":"Bing Crosby With Ken Darby Singers & John Scott Trotter & His Orchestra","this_week":19,"last_week":34,"peak_position":12,"weeks_on_chart":41},{"song":"Mutt","artist":"Leon Thomas","this_week":20,"last_week":9,"peak_position":6,"weeks_on_chart":44},{"song":"Jingle Bells","artist":"Frank Sinatra With The Orchestra & Chorus Of Gordon Jenkins","this_week":21,"last_week":31,"peak_position":16,"weeks_on_chart":20},{"song":"Run Rudolph Run","artist":"Chuck Berry","this_week":22,"last_week":39,"peak_position":10,"weeks_on_chart":28},{"song":"Back To Friends","artist":"sombr","this_week":23,"last_week":15,"peak_position":10,"weeks_on_chart":36},{"song":"It\'s Beginning To Look A Lot Like Christmas","artist":"Perry Como And The Fontane Sisters With Mitchell Ayres And His Orchestra","this_week":24,"last_week":38,"peak_position":12,"weeks_on_chart":29},{"song":"Opalite","artist":"Taylor Swift","this_week":25,"last_week":10,"peak_position":2,"weeks_on_chart":9},{"song":"Folded","artist":"Kehlani","this_week":26,"last_week":12,"peak_position":7,"weeks_on_chart":25},{"song":"Choosin\' Texas","artist":"Ella Langley","this_week":27,"last_week":11,"peak_position":11,"weeks_on_chart":7},{"song":"Daisies","artist":"Justin Bieber","this_week":28,"last_week":14,"peak_position":2,"weeks_on_chart":21},{"song":"Deck The Halls","artist":"Nat King Cole","this_week":29,"last_week":45,"peak_position":16,"weeks_on_chart":19},{"song":"Santa Baby","artist":"Eartha Kitt With Henri Rene And His Orchestra","this_week":30,"last_week":49,"peak_position":20,"weeks_on_chart":14},{"song":"Blue Christmas","artist":"Elvis Presley","this_week":31,"last_week":50,"peak_position":18,"weeks_on_chart":18},{"song":"Here Comes Santa Claus (Right Down Santa Claus Lane)","artist":"Gene Autry","this_week":32,"last_week":42,"peak_position":21,"weeks_on_chart":26},{"song":"Wonderful Christmastime","artist":"Paul McCartney","this_week":33,"last_week":null,"peak_position":26,"weeks_on_chart":17},{"song":"Please Come Home For Christmas","artist":"Eagles","this_week":34,"last_week":null,"peak_position":18,"weeks_on_chart":18},{"song":"Like It\'s Christmas","artist":"Jonas Brothers","this_week":35,"last_week":null,"peak_position":35,"weeks_on_chart":10},{"song":"Holly Jolly Christmas","artist":"Michael Buble","this_week":36,"last_week":null,"peak_position":36,"weeks_on_chart":2},{"song":"Rudolph The Red-Nosed Reindeer","artist":"Gene Autry & The Pinafores","this_week":37,"last_week":null,"peak_position":16,"weeks_on_chart":30},{"song":"Christmastime Is Here","artist":"Vince Guaraldi Trio","this_week":38,"last_week":null,"peak_position":31,"weeks_on_chart":8},{"song":"Little Saint Nick","artist":"The Beach Boys","this_week":39,"last_week":null,"peak_position":25,"weeks_on_chart":12},{"song":"Santa, Can\'t You Hear Me","artist":"Kelly Clarkson & Ariana Grande","this_week":40,"last_week":null,"peak_position":40,"weeks_on_chart":5},{"song":"You\'re A Mean One, Mr. Grinch","artist":"Thurl Ravenscroft","this_week":41,"last_week":null,"peak_position":31,"weeks_on_chart":14},{"song":"It Depends","artist":"Chris Brown Featuring Bryson Tiller","this_week":42,"last_week":28,"peak_position":16,"weeks_on_chart":19},{"song":"Merry Christmas","artist":"Ed Sheeran & Elton John","this_week":43,"last_week":null,"peak_position":38,"weeks_on_chart":9},{"song":"Mistletoe","artist":"Justin Bieber","this_week":44,"last_week":null,"peak_position":11,"weeks_on_chart":15},{"song":"Tit For Tat","artist":"Tate McRae","this_week":45,"last_week":26,"peak_position":3,"weeks_on_chart":10},{"song":"Santa Claus Is Comin\' To Town","artist":"Jackson 5","this_week":46,"last_week":null,"peak_position":30,"weeks_on_chart":12},{"song":"So Easy (To Fall In Love)","artist":"Olivia Dean","this_week":47,"last_week":27,"peak_position":18,"weeks_on_chart":10},{"song":"Baby It\'s Cold Outside","artist":"Dean Martin","this_week":48,"last_week":null,"peak_position":36,"weeks_on_chart":3},{"song":"Winter Wonderland","artist":"Darlene Love","this_week":49,"last_week":null,"peak_position":48,"weeks_on_chart":2},{"song":"This Christmas","artist":"Donny Hathaway","this_week":50,"last_week":null,"peak_position":34,"weeks_on_chart":7},{"song":"Tears","artist":"Sabrina Carpenter","this_week":51,"last_week":33,"peak_position":3,"weeks_on_chart":14},{"song":"Don\'t Mind If I Do","artist":"Riley Green Featuring Ella Langley","this_week":52,"last_week":32,"peak_position":32,"weeks_on_chart":18},{"song":"Where Is My Husband!","artist":"RAYE","this_week":53,"last_week":37,"peak_position":37,"weeks_on_chart":10},{"song":"wgft","artist":"Gunna Featuring Burna Boy","this_week":54,"last_week":47,"peak_position":40,"weeks_on_chart":17},{"song":"Gabriela","artist":"KATSEYE","this_week":55,"last_week":41,"peak_position":31,"weeks_on_chart":20},{"song":"Happen To Me","artist":"Russell Dickerson","this_week":56,"last_week":51,"peak_position":28,"weeks_on_chart":33},{"song":"20 Cigarettes","artist":"Morgan Wallen","this_week":57,"last_week":55,"peak_position":20,"weeks_on_chart":28},{"song":"Nice To Meet You","artist":"Myles Smith","this_week":58,"last_week":61,"peak_position":54,"weeks_on_chart":26},{"song":"6 Months Later","artist":"Megan Moroney","this_week":59,"last_week":48,"peak_position":30,"weeks_on_chart":24},{"song":"Is It A Crime","artist":"Mariah The Scientist & Kali Uchis","this_week":60,"last_week":57,"peak_position":45,"weeks_on_chart":17},{"song":"Yukon","artist":"Justin Bieber","this_week":61,"last_week":58,"peak_position":17,"weeks_on_chart":21},{"song":"Hell At Night","artist":"BigXthaPlug Featuring Ella Langley","this_week":62,"last_week":46,"peak_position":35,"weeks_on_chart":17},{"song":"House Again","artist":"Hudson Westbrook","this_week":63,"last_week":60,"peak_position":47,"weeks_on_chart":33},{"song":"Better Me For You (Brown Eyes)","artist":"Max McNown","this_week":64,"last_week":63,"peak_position":50,"weeks_on_chart":25},{"song":"A Couple Minutes","artist":"Olivia Dean","this_week":65,"last_week":65,"peak_position":55,"weeks_on_chart":6},{"song":"Nobody\'s Girl","artist":"Tate McRae","this_week":66,"last_week":29,"peak_position":29,"weeks_on_chart":2},{"song":"Shot Callin","artist":"YoungBoy Never Broke Again","this_week":67,"last_week":64,"peak_position":43,"weeks_on_chart":12},{"song":"Elizabeth Taylor","artist":"Taylor Swift","this_week":68,"last_week":53,"peak_position":3,"weeks_on_chart":9},{"song":"3,2,1","artist":"Tucker Wetmore","this_week":69,"last_week":87,"peak_position":69,"weeks_on_chart":7},{"song":"Dracula","artist":"Tame Impala","this_week":70,"last_week":67,"peak_position":30,"weeks_on_chart":10},{"song":"Take Me Thru Dere","artist":"Metro Boomin, Quavo, Breskii & YKNIECE","this_week":71,"last_week":70,"peak_position":69,"weeks_on_chart":10},{"song":"The Fall","artist":"Cody Johnson","this_week":72,"last_week":73,"peak_position":68,"weeks_on_chart":10},{"song":"Travelin\' Soldier","artist":"Cody Johnson","this_week":73,"last_week":62,"peak_position":12,"weeks_on_chart":4},{"song":"Sugar On My Tongue","artist":"Tyler, The Creator","this_week":74,"last_week":76,"peak_position":41,"weeks_on_chart":20},{"song":"12 To 12","artist":"sombr","this_week":75,"last_week":81,"peak_position":41,"weeks_on_chart":16},{"song":"Darlin\'","artist":"Chase Matthew","this_week":76,"last_week":75,"peak_position":52,"weeks_on_chart":11},{"song":"Amen","artist":"Shaboozey & Jelly Roll","this_week":77,"last_week":85,"peak_position":56,"weeks_on_chart":30},{"song":"Last One To Know","artist":"Gavin Adcock","this_week":78,"last_week":72,"peak_position":54,"weeks_on_chart":16},{"song":"Favorite Country Song","artist":"HARDY","this_week":79,"last_week":86,"peak_position":79,"weeks_on_chart":6},{"song":"Father Figure","artist":"Taylor Swift","this_week":80,"last_week":69,"peak_position":4,"weeks_on_chart":9},{"song":"Camera","artist":"Ed Sheeran","this_week":81,"last_week":90,"peak_position":58,"weeks_on_chart":12},{"song":"ErrTime","artist":"Cardi B","this_week":82,"last_week":79,"peak_position":43,"weeks_on_chart":10},{"song":"Back In The Saddle","artist":"Luke Combs","this_week":83,"last_week":74,"peak_position":22,"weeks_on_chart":19},{"song":"Wi$h Li$t","artist":"Taylor Swift","this_week":84,"last_week":71,"peak_position":6,"weeks_on_chart":9},{"song":"Cowgirl","artist":"Parmalee","this_week":85,"last_week":null,"peak_position":85,"weeks_on_chart":1},{"song":"Shake The Snow Globe","artist":"Gwen Stefani","this_week":86,"last_week":null,"peak_position":86,"weeks_on_chart":1},{"song":"Days Like These","artist":"Luke Combs","this_week":87,"last_week":88,"peak_position":79,"weeks_on_chart":6},{"song":"Anything But Love","artist":"Tate McRae","this_week":88,"last_week":44,"peak_position":44,"weeks_on_chart":2},{"song":"What Kinda Man","artist":"Parker McCollum","this_week":89,"last_week":66,"peak_position":66,"weeks_on_chart":12},{"song":"How Far Does A Goodbye Go","artist":"Jason Aldean","this_week":90,"last_week":92,"peak_position":80,"weeks_on_chart":8},{"song":"Nice To Each Other","artist":"Olivia Dean","this_week":91,"last_week":78,"peak_position":78,"weeks_on_chart":8},{"song":"Gone Gone Gone","artist":"David Guetta, Teddy Swims & Tones And I","this_week":92,"last_week":null,"peak_position":92,"weeks_on_chart":1},{"song":"The Dead Dance","artist":"Lady Gaga","this_week":93,"last_week":94,"peak_position":40,"weeks_on_chart":13},{"song":"Went Legit","artist":"G Herbo","this_week":94,"last_week":89,"peak_position":70,"weeks_on_chart":20},{"song":"Sienna","artist":"The Marias","this_week":95,"last_week":null,"peak_position":74,"weeks_on_chart":12},{"song":"For Good","artist":"Cynthia Erivo & Ariana Grande","this_week":96,"last_week":43,"peak_position":43,"weeks_on_chart":2},{"song":"No Good Deed","artist":"Cynthia Erivo","this_week":97,"last_week":56,"peak_position":56,"weeks_on_chart":2},{"song":"Let Alone The One You Love","artist":"Olivia Dean","this_week":98,"last_week":95,"peak_position":95,"weeks_on_chart":3},{"song":"The Life Of A Showgirl","artist":"Taylor Swift Featuring Sabrina Carpenter","this_week":99,"last_week":80,"peak_position":8,"weeks_on_chart":9},{"song":"When Did You Get Hot?","artist":"Sabrina Carpenter","this_week":100,"last_week":96,"peak_position":17,"weeks_on_chart":14}]}'

In [13]:
data = json.loads(response.content)
s = json.dumps(data, indent=4, sort_keys=True)
file3 = pd.read_json(s)

/tmp/ipykernel_835/1196471522.py:3: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  file3 = pd.read_json(s)

In [15]:
display(pd.json_normalize(file3['data']))

,artist,last_week,peak_position,song,this_week,weeks_on_chart
0,Mariah Carey,5.0,1,All I Want For Christmas Is You,1,76
1,Wham!,6.0,2,Last Christmas,2,50
2,Brenda Lee,7.0,1,Rockin' Around The Christmas Tree,3,68
3,Bobby Helms,8.0,3,Jingle Bell Rock,4,65
4,"HUNTR/X: EJAE, Audrey Nuna & REI AMI",2.0,1,Golden,5,24
...,...,...,...,...,...,...
95,Cynthia Erivo & Ariana Grande,43.0,43,For Good,96,2
96,Cynthia Erivo,56.0,56,No Good Deed,97,2
97,Olivia Dean,95.0,95,Let Alone The One You Love,98,3
98,Taylor Swift Featuring Sabrina Carpenter,80.0,8,The Life Of A Showgirl,99,9
99,Sabrina Carpenter,96.0,17,When Did You Get Hot?,100,14

In [19]:
file_merged = pd.concat([file3['date'], pd.json_normalize(file3['data'])], axis=1)

In [20]:
file_merged = file_merged.iloc[:, [0,4,1,2,3,,5]]
['','','','','','','']
file_merged

,date,artist,last_week,peak_position,song,this_week,weeks_on_chart
0,2025-12-13,Mariah Carey,5.0,1,All I Want For Christmas Is You,1,76
1,2025-12-13,Wham!,6.0,2,Last Christmas,2,50
2,2025-12-13,Brenda Lee,7.0,1,Rockin' Around The Christmas Tree,3,68
3,2025-12-13,Bobby Helms,8.0,3,Jingle Bell Rock,4,65
4,2025-12-13,"HUNTR/X: EJAE, Audrey Nuna & REI AMI",2.0,1,Golden,5,24
...,...,...,...,...,...,...,...
95,2025-12-13,Cynthia Erivo & Ariana Grande,43.0,43,For Good,96,2
96,2025-12-13,Cynthia Erivo,56.0,56,No Good Deed,97,2
97,2025-12-13,Olivia Dean,95.0,95,Let Alone The One You Love,98,3
98,2025-12-13,Taylor Swift Featuring Sabrina Carpenter,80.0,8,The Life Of A Showgirl,99,9
99,2025-12-13,Sabrina Carpenter,96.0,17,When Did You Get Hot?,100,14

In [21]:
billboardOAT = pd.read_parquet('raw/billboard/billboard_100_OAT.parquet', engine='pyarrow')

In [22]:
billboardOAT

,date,song,artist,this_week,last_week,peak_position,weeks_on_chart
0,1958-08-04,Poor Little Fool,Ricky Nelson,1.0,NaN,1.0,1.0
1,1958-08-04,Patricia,Perez Prado And His Orchestra,2.0,NaN,2.0,1.0
2,1958-08-04,Splish Splash,Bobby Darin,3.0,NaN,3.0,1.0
3,1958-08-04,Hard Headed Woman,Elvis Presley With The Jordanaires,4.0,NaN,4.0,1.0
4,1958-08-04,When,Kalin Twins,5.0,NaN,5.0,1.0
...,...,...,...,...,...,...,...
351295,2025-11-29,Baller,"Summer Walker, Glorilla, Sexyy Red & Monaleo",96.0,NaN,96.0,1.0
351296,2025-11-29,Let Alone The One You Love,Olivia Dean,97.0,NaN,97.0,1.0
351297,2025-11-29,Losin' Streak,Blake Roman,98.0,NaN,98.0,1.0
351298,2025-11-29,Favorite Country Song,HARDY,99.0,90.0,90.0,4.0
351299,2025-11-29,How Far Does A Goodbye Go,Jason Aldean,100.0,80.0,80.0,6.0

In [26]:
oat = pd.concat([billboardOAT, file_merged],ignore_index=True)
oat

,date,song,artist,this_week,last_week,peak_position,weeks_on_chart
0,1958-08-04,Poor Little Fool,Ricky Nelson,1.0,NaN,1.0,1.0
1,1958-08-04,Patricia,Perez Prado And His Orchestra,2.0,NaN,2.0,1.0
2,1958-08-04,Splish Splash,Bobby Darin,3.0,NaN,3.0,1.0
3,1958-08-04,Hard Headed Woman,Elvis Presley With The Jordanaires,4.0,NaN,4.0,1.0
4,1958-08-04,When,Kalin Twins,5.0,NaN,5.0,1.0
...,...,...,...,...,...,...,...
351395,2025-12-13 00:00:00,For Good,Cynthia Erivo & Ariana Grande,96.0,43.0,43.0,2.0
351396,2025-12-13 00:00:00,No Good Deed,Cynthia Erivo,97.0,56.0,56.0,2.0
351397,2025-12-13 00:00:00,Let Alone The One You Love,Olivia Dean,98.0,95.0,95.0,3.0
351398,2025-12-13 00:00:00,The Life Of A Showgirl,Taylor Swift Featuring Sabrina Carpenter,99.0,80.0,8.0,9.0
351399,2025-12-13 00:00:00,When Did You Get Hot?,Sabrina Carpenter,100.0,96.0,17.0,14.0

In [27]:
oat['date'] = pd.to_datetime(oat['date']).dt.date
oat

,date,song,artist,this_week,last_week,peak_position,weeks_on_chart
0,1958-08-04,Poor Little Fool,Ricky Nelson,1.0,NaN,1.0,1.0
1,1958-08-04,Patricia,Perez Prado And His Orchestra,2.0,NaN,2.0,1.0
2,1958-08-04,Splish Splash,Bobby Darin,3.0,NaN,3.0,1.0
3,1958-08-04,Hard Headed Woman,Elvis Presley With The Jordanaires,4.0,NaN,4.0,1.0
4,1958-08-04,When,Kalin Twins,5.0,NaN,5.0,1.0
...,...,...,...,...,...,...,...
351395,2025-12-13,For Good,Cynthia Erivo & Ariana Grande,96.0,43.0,43.0,2.0
351396,2025-12-13,No Good Deed,Cynthia Erivo,97.0,56.0,56.0,2.0
351397,2025-12-13,Let Alone The One You Love,Olivia Dean,98.0,95.0,95.0,3.0
351398,2025-12-13,The Life Of A Showgirl,Taylor Swift Featuring Sabrina Carpenter,99.0,80.0,8.0,9.0
351399,2025-12-13,When Did You Get Hot?,Sabrina Carpenter,100.0,96.0,17.0,14.0

# Partie Analyse et création dossier Spotify

In [6]:
file = pd.read_json("raw/spotify/artist/top_tracks_Anirudh Ravichander_2025-12-04.json")
file2 = pd.json_normalize(file.tracks)
display(file2)

,artists,disc_number,duration_ms,explicit,href,id,is_local,is_playable,name,popularity,...,album.images,album.is_playable,album.name,album.release_date,album.release_date_precision,album.total_tracks,album.type,album.uri,external_ids.isrc,external_urls.spotify
0,[{'external_urls': {'spotify': 'https://open.s...,1,217627,False,https://api.spotify.com/v1/tracks/7MrdHOL2aoWf...,7MrdHOL2aoWfT16CncgNei,False,True,Monica,68,...,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",True,Coolie (Original Motion Picture Soundtrack),2025-08-02,day,8,album,spotify:album:3roEiD2gUP1LHPHwUPbXs1,QMDA62550185,https://open.spotify.com/track/7MrdHOL2aoWfT16...
1,[{'external_urls': {'spotify': 'https://open.s...,1,197104,False,https://api.spotify.com/v1/tracks/28keFvZn4UVR...,28keFvZn4UVRi4I8Rj4GjY,False,True,"Thalapathy Kacheri (From ""Jana Nayagan"")",76,...,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",True,"Thalapathy Kacheri (From ""Jana Nayagan"")",2025-11-08,day,1,album,spotify:album:0TthxobhZuRUVweIhTUwuc,INS182504154,https://open.spotify.com/track/28keFvZn4UVRi4I...
2,[{'external_urls': {'spotify': 'https://open.s...,1,206627,False,https://api.spotify.com/v1/tracks/3JC5Xx48KqzY...,3JC5Xx48KqzYYlbTr6weCv,False,True,Powerhouse,68,...,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",True,Coolie (Original Motion Picture Soundtrack),2025-08-02,day,8,album,spotify:album:3roEiD2gUP1LHPHwUPbXs1,QMDA62587043,https://open.spotify.com/track/3JC5Xx48KqzYYlb...
3,[{'external_urls': {'spotify': 'https://open.s...,1,200373,False,https://api.spotify.com/v1/tracks/3xMHXmedL5Rv...,3xMHXmedL5Rvfxmiar9Ryv,False,True,Chaleya,69,...,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",True,Jawan,2023-09-05,day,7,album,spotify:album:3WLJmMZUeDOuERFAk1Mxs6,INS182302348,https://open.spotify.com/track/3xMHXmedL5Rvfxm...
4,[{'external_urls': {'spotify': 'https://open.s...,1,222063,False,https://api.spotify.com/v1/tracks/1bxzr3JK05fM...,1bxzr3JK05fMTcweGAZUHp,False,True,"Chuttamalle (From ""Devara Part 1"")",74,...,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",True,"Chuttamalle (From ""Devara Part 1"")",2024-08-05,day,1,album,spotify:album:77bk7awXNSGEQkZTcTp2Gj,INS182402313,https://open.spotify.com/track/1bxzr3JK05fMTcw...
5,[{'external_urls': {'spotify': 'https://open.s...,1,188505,False,https://api.spotify.com/v1/tracks/7vKddq80IImH...,7vKddq80IImHdiz83ZU2zF,False,True,Monica,65,...,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",True,Coolie (Original Motion Picture Soundtrack),2025-08-12,day,8,album,spotify:album:22mwh2WQgpVT4j5CaNGWYl,QMDA62550221,https://open.spotify.com/track/7vKddq80IImHdiz...
6,[{'external_urls': {'spotify': 'https://open.s...,1,256945,False,https://api.spotify.com/v1/tracks/4KUQFOGTaHrg...,4KUQFOGTaHrggl3hfMoaAe,False,True,"Kannamma - From ""Ispade Rajavum Idhaya Raniyum""",67,...,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",True,"Kannamma (From ""Ispade Rajavum Idhaya Raniyum"")",2019-01-11,day,1,album,spotify:album:7bgFFKluLbu4PRIRzdink9,INT201901935,https://open.spotify.com/track/4KUQFOGTaHrggl3...
7,[{'external_urls': {'spotify': 'https://open.s...,1,235629,False,https://api.spotify.com/v1/tracks/3CA9CjRf7IU2...,3CA9CjRf7IU2Ukz3GuYInP,False,True,Manasilaayo,68,...,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",True,Vettaiyan (Original Motion Picture Soundtrack),2024-10-14,day,9,album,spotify:album:6Xw7XAQQwpsy9KfUnJTrHz,INS172409897,https://open.spotify.com/track/3CA9CjRf7IU2Ukz...
8,[{'external_urls': {'spotify': 'https://open.s...,1,240845,False,https://api.spotify.com/v1/tracks/2unhBSPWS4Cp...,2unhBSPWS4Cpn5EfIKbAxG,False,True,Thangapoovey,56,...,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",True,Madharaasi (Original Motion Picture Soundtrack),2025-08-27,day,9,album,spotify:album:7HUzJeQvFdJDWueJi6pofV,INT132500505,https://open.spotify.com/track/2unhBSPWS4Cpn5E...
9,[{'external_urls': {'spotify': 'https://open.s...,1,207219,False,https://api.spotify.com/v1/tracks/07dj2zpMixBX...,07dj2zpMixBXxQuwp4erRD,False,True,Salambala,56,...,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",True,Madharaasi (Original Motion Picture Soundtrack),2025-08-27,day,9,album,spotify:album:7HUzJeQvFdJDWueJi6pofV,INT132500431,https://open.spotify.com/track/07dj2zpMixBXxQu...

In [3]:
file2.iloc[:,10:19]

,preview_url,track_number,type,uri,album.album_type,album.artists,album.external_urls.spotify,album.href,album.id
0,None,1,track,spotify:track:2BwO5K8Q7EPAJSGze3AAh9,album,[{'external_urls': {'spotify': 'https://open.s...,https://open.spotify.com/album/1aqg30bNvLSWgSh...,https://api.spotify.com/v1/albums/1aqg30bNvLSW...,1aqg30bNvLSWgShZgX4oop
1,None,2,track,spotify:track:42VUCXerQ5qTr4Qp6PhKo4,album,[{'external_urls': {'spotify': 'https://open.s...,https://open.spotify.com/album/1aqg30bNvLSWgSh...,https://api.spotify.com/v1/albums/1aqg30bNvLSW...,1aqg30bNvLSWgShZgX4oop
2,None,12,track,spotify:track:5eXgqtg3T8Av0m1FUaGHex,album,[{'external_urls': {'spotify': 'https://open.s...,https://open.spotify.com/album/4a6NzYL1YHRUgx9...,https://api.spotify.com/v1/albums/4a6NzYL1YHRU...,4a6NzYL1YHRUgx9e3YZI6I
3,None,7,track,spotify:track:2HRqTpkrJO5ggZyyK6NPWz,album,[{'external_urls': {'spotify': 'https://open.s...,https://open.spotify.com/album/3iPSVi54hsacKKl...,https://api.spotify.com/v1/albums/3iPSVi54hsac...,3iPSVi54hsacKKl1xIR2eH
4,None,8,track,spotify:track:0je57Uq5eTk1wrPzn9sWbl,album,[{'external_urls': {'spotify': 'https://open.s...,https://open.spotify.com/album/1aqg30bNvLSWgSh...,https://api.spotify.com/v1/albums/1aqg30bNvLSW...,1aqg30bNvLSWgShZgX4oop
5,None,1,track,spotify:track:5G2f63n7IPVPPjfNIGih7Q,album,[{'external_urls': {'spotify': 'https://open.s...,https://open.spotify.com/album/3iPSVi54hsacKKl...,https://api.spotify.com/v1/albums/3iPSVi54hsac...,3iPSVi54hsacKKl1xIR2eH
6,None,6,track,spotify:track:4SRShYMtFIGgnOU7iBicMH,album,[{'external_urls': {'spotify': 'https://open.s...,https://open.spotify.com/album/1aqg30bNvLSWgSh...,https://api.spotify.com/v1/albums/1aqg30bNvLSW...,1aqg30bNvLSWgShZgX4oop
7,None,2,track,spotify:track:2tHwzyyOLoWSFqYNjeVMzj,album,[{'external_urls': {'spotify': 'https://open.s...,https://open.spotify.com/album/3iPSVi54hsacKKl...,https://api.spotify.com/v1/albums/3iPSVi54hsac...,3iPSVi54hsacKKl1xIR2eH
8,None,11,track,spotify:track:25jgQBxuUkGDdCG1WGKKN9,album,[{'external_urls': {'spotify': 'https://open.s...,https://open.spotify.com/album/1aqg30bNvLSWgSh...,https://api.spotify.com/v1/albums/1aqg30bNvLSW...,1aqg30bNvLSWgShZgX4oop
9,None,9,track,spotify:track:6dgUya35uo964z7GZXM07g,album,[{'external_urls': {'spotify': 'https://open.s...,https://open.spotify.com/album/5kDmlA2g9Y1YCbN...,https://api.spotify.com/v1/albums/5kDmlA2g9Y1Y...,5kDmlA2g9Y1YCbNo2Ufxlz

In [4]:
file2.iloc[:,19:29]

,album.images,album.is_playable,album.name,album.release_date,album.release_date_precision,album.total_tracks,album.type,album.uri,external_ids.isrc,external_urls.spotify
0,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",True,Man’s Best Friend,2025-08-29,day,12,album,spotify:album:1aqg30bNvLSWgShZgX4oop,USUM72504354,https://open.spotify.com/track/2BwO5K8Q7EPAJSG...
1,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",True,Man’s Best Friend,2025-08-29,day,12,album,spotify:album:1aqg30bNvLSWgShZgX4oop,USUM72504355,https://open.spotify.com/track/42VUCXerQ5qTr4Q...
2,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",True,The Life of a Showgirl,2025-10-03,day,12,album,spotify:album:4a6NzYL1YHRUgx9e3YZI6I,USUG12506447,https://open.spotify.com/track/5eXgqtg3T8Av0m1...
3,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",True,Short n' Sweet,2024-08-23,day,12,album,spotify:album:3iPSVi54hsacKKl1xIR2eH,USUM72403305,https://open.spotify.com/track/2HRqTpkrJO5ggZy...
4,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",True,Man’s Best Friend,2025-08-29,day,12,album,spotify:album:1aqg30bNvLSWgShZgX4oop,USUM72504446,https://open.spotify.com/track/0je57Uq5eTk1wrP...
5,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",True,Short n' Sweet,2024-08-23,day,12,album,spotify:album:3iPSVi54hsacKKl1xIR2eH,USUM72404100,https://open.spotify.com/track/5G2f63n7IPVPPjf...
6,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",True,Man’s Best Friend,2025-08-29,day,12,album,spotify:album:1aqg30bNvLSWgShZgX4oop,USUM72504443,https://open.spotify.com/track/4SRShYMtFIGgnOU...
7,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",True,Short n' Sweet,2024-08-23,day,12,album,spotify:album:3iPSVi54hsacKKl1xIR2eH,USUM72404101,https://open.spotify.com/track/2tHwzyyOLoWSFqY...
8,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",True,Man’s Best Friend,2025-08-29,day,12,album,spotify:album:1aqg30bNvLSWgShZgX4oop,USUM72504449,https://open.spotify.com/track/25jgQBxuUkGDdCG...
9,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",True,emails i can't send,2022-07-15,day,13,album,spotify:album:5kDmlA2g9Y1YCbNo2Ufxlz,USUM72210708,https://open.spotify.com/track/6dgUya35uo964z7...

In [5]:
pd.json_normalize(file2.artists[0])['external_urls.spotify'].values

array(['https://open.spotify.com/artist/74KM79TiuVKeVCqs8QtB0B'],
      dtype=object)

In [6]:
pd.json_normalize(file2.artists[1])

,href,id,name,type,uri,external_urls.spotify
0,https://api.spotify.com/v1/artists/74KM79TiuVK...,74KM79TiuVKeVCqs8QtB0B,Sabrina Carpenter,artist,spotify:artist:74KM79TiuVKeVCqs8QtB0B,https://open.spotify.com/artist/74KM79TiuVKeVC...

In [7]:
file2["href"].values

array(['https://api.spotify.com/v1/tracks/2BwO5K8Q7EPAJSGze3AAh9',
       'https://api.spotify.com/v1/tracks/42VUCXerQ5qTr4Qp6PhKo4',
       'https://api.spotify.com/v1/tracks/5eXgqtg3T8Av0m1FUaGHex',
       'https://api.spotify.com/v1/tracks/2HRqTpkrJO5ggZyyK6NPWz',
       'https://api.spotify.com/v1/tracks/0je57Uq5eTk1wrPzn9sWbl',
       'https://api.spotify.com/v1/tracks/5G2f63n7IPVPPjfNIGih7Q',
       'https://api.spotify.com/v1/tracks/4SRShYMtFIGgnOU7iBicMH',
       'https://api.spotify.com/v1/tracks/2tHwzyyOLoWSFqYNjeVMzj',
       'https://api.spotify.com/v1/tracks/25jgQBxuUkGDdCG1WGKKN9',
       'https://api.spotify.com/v1/tracks/6dgUya35uo964z7GZXM07g'],
      dtype=object)

In [8]:
pd.json_normalize(file2.artists[1])

,href,id,name,type,uri,external_urls.spotify
0,https://api.spotify.com/v1/artists/74KM79TiuVK...,74KM79TiuVKeVCqs8QtB0B,Sabrina Carpenter,artist,spotify:artist:74KM79TiuVKeVCqs8QtB0B,https://open.spotify.com/artist/74KM79TiuVKeVC...

In [9]:
pd.json_normalize(file2['album.images'])

,0,1,2
0,"{'height': 640, 'url': 'https://i.scdn.co/imag...","{'height': 300, 'url': 'https://i.scdn.co/imag...","{'height': 64, 'url': 'https://i.scdn.co/image..."
1,"{'height': 640, 'url': 'https://i.scdn.co/imag...","{'height': 300, 'url': 'https://i.scdn.co/imag...","{'height': 64, 'url': 'https://i.scdn.co/image..."
2,"{'height': 640, 'url': 'https://i.scdn.co/imag...","{'height': 300, 'url': 'https://i.scdn.co/imag...","{'height': 64, 'url': 'https://i.scdn.co/image..."
3,"{'height': 640, 'url': 'https://i.scdn.co/imag...","{'height': 300, 'url': 'https://i.scdn.co/imag...","{'height': 64, 'url': 'https://i.scdn.co/image..."
4,"{'height': 640, 'url': 'https://i.scdn.co/imag...","{'height': 300, 'url': 'https://i.scdn.co/imag...","{'height': 64, 'url': 'https://i.scdn.co/image..."
5,"{'height': 640, 'url': 'https://i.scdn.co/imag...","{'height': 300, 'url': 'https://i.scdn.co/imag...","{'height': 64, 'url': 'https://i.scdn.co/image..."
6,"{'height': 640, 'url': 'https://i.scdn.co/imag...","{'height': 300, 'url': 'https://i.scdn.co/imag...","{'height': 64, 'url': 'https://i.scdn.co/image..."
7,"{'height': 640, 'url': 'https://i.scdn.co/imag...","{'height': 300, 'url': 'https://i.scdn.co/imag...","{'height': 64, 'url': 'https://i.scdn.co/image..."
8,"{'height': 640, 'url': 'https://i.scdn.co/imag...","{'height': 300, 'url': 'https://i.scdn.co/imag...","{'height': 64, 'url': 'https://i.scdn.co/image..."
9,"{'height': 640, 'url': 'https://i.scdn.co/imag...","{'height': 300, 'url': 'https://i.scdn.co/imag...","{'height': 64, 'url': 'https://i.scdn.co/image..."

In [10]:
pd.json_normalize(pd.json_normalize(file2['album.images'])[0]).values

array([[640,
        'https://i.scdn.co/image/ab67616d0000b273b1863bf95557ea7f357c4947',
        640],
       [640,
        'https://i.scdn.co/image/ab67616d0000b273b1863bf95557ea7f357c4947',
        640],
       [640,
        'https://i.scdn.co/image/ab67616d0000b273d7812467811a7da6e6a44902',
        640],
       [640,
        'https://i.scdn.co/image/ab67616d0000b273fd8d7a8d96871e791cb1f626',
        640],
       [640,
        'https://i.scdn.co/image/ab67616d0000b273b1863bf95557ea7f357c4947',
        640],
       [640,
        'https://i.scdn.co/image/ab67616d0000b273fd8d7a8d96871e791cb1f626',
        640],
       [640,
        'https://i.scdn.co/image/ab67616d0000b273b1863bf95557ea7f357c4947',
        640],
       [640,
        'https://i.scdn.co/image/ab67616d0000b273fd8d7a8d96871e791cb1f626',
        640],
       [640,
        'https://i.scdn.co/image/ab67616d0000b273b1863bf95557ea7f357c4947',
        640],
       [640,
        'https://i.scdn.co/image/ab67616d0000b273700f7bf79c9f063ad0362bdf',
        640]], dtype=object)

In [11]:
pd.json_normalize(file2['album.images'][1])

   height                                                url  width
0     640  https://i.scdn.co/image/ab67616d0000b273b1863b...    640
1     300  https://i.scdn.co/image/ab67616d00001e02b1863b...    300
2      64  https://i.scdn.co/image/ab67616d00004851b1863b...     64

# Partie Analyse et création dossier Billboard

In [3]:
file_new = pd.read_json("all.json")

In [4]:
display(file_new)

           date                                               data
0    1958-08-04  [{'song': 'Poor Little Fool', 'artist': 'Ricky...
1    1958-08-11  [{'song': 'Poor Little Fool', 'artist': 'Ricky...
2    1958-08-18  [{'song': 'Nel Blu Dipinto Di Blu (Volare)', '...
3    1958-08-25  [{'song': 'Little Star', 'artist': 'The Elegan...
4    1958-09-01  [{'song': 'Nel Blu Dipinto Di Blu (Volare)', '...
...         ...                                                ...
3510 2025-11-15  [{'song': 'The Fate Of Ophelia', 'artist': 'Ta...
3511 2025-11-22  [{'song': 'The Fate Of Ophelia', 'artist': 'Ta...
3512 2025-11-29  [{'song': 'The Fate Of Ophelia', 'artist': 'Ta...
3513 2025-12-06  [{'song': 'The Fate Of Ophelia', 'artist': 'Ta...
3514 2025-12-13  [{'song': 'All I Want For Christmas Is You', '...

[3515 rows x 2 columns]

In [5]:
pd.json_normalize(file_new.data)

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,"{'song': 'Poor Little Fool', 'artist': 'Ricky ...","{'song': 'Patricia', 'artist': 'Perez Prado An...","{'song': 'Splish Splash', 'artist': 'Bobby Dar...","{'song': 'Hard Headed Woman', 'artist': 'Elvis...","{'song': 'When', 'artist': 'Kalin Twins', 'thi...","{'song': 'Rebel-'rouser', 'artist': 'Duane Edd...","{'song': 'Yakety Yak', 'artist': 'The Coasters...","{'song': 'My True Love', 'artist': 'Jack Scott...","{'song': 'Willie And The Hand Jive', 'artist':...","{'song': 'Fever', 'artist': 'Peggy Lee', 'this...",...,{'song': 'The Purple People Eater Meets The Wi...,"{'song': 'Bird Dog', 'artist': 'The Everly Bro...","{'song': 'Are You Really Mine', 'artist': 'Jim...",{'song': 'She Was Only Seventeen (He Was One Y...,"{'song': 'Little Mary', 'artist': 'Fats Domino...","{'song': 'Over And Over', 'artist': 'Thurston ...","{'song': 'I Believe In You', 'artist': 'Robert...","{'song': 'Little Serenade', 'artist': 'The Ame...",{'song': 'I'll Get By (As Long As I Have You)'...,"{'song': 'Judy', 'artist': 'Frankie Vaughan', ..."
1,"{'song': 'Poor Little Fool', 'artist': 'Ricky ...","{'song': 'Nel Blu Dipinto Di Blu (Volare)', 'a...","{'song': 'Patricia', 'artist': 'Perez Prado An...","{'song': 'Splish Splash', 'artist': 'Bobby Dar...","{'song': 'When', 'artist': 'Kalin Twins', 'thi...","{'song': 'My True Love', 'artist': 'Jack Scott...","{'song': 'Hard Headed Woman', 'artist': 'Elvis...","{'song': 'Rebel-'rouser', 'artist': 'Duane Edd...","{'song': 'Just A Dream', 'artist': 'Jimmy Clan...","{'song': 'Willie And The Hand Jive', 'artist':...",...,"{'song': 'All I Have To Do Is Dream', 'artist'...","{'song': 'La Paloma', 'artist': 'Billy Vaughn ...","{'song': 'I Believe In You', 'artist': 'Robert...","{'song': 'Midnighter', 'artist': 'The Champs',...","{'song': 'Chariot Rock', 'artist': 'The Champs...","{'song': 'Down In Virginia', 'artist': 'Jimmy ...","{'song': 'Sunday Barbecue', 'artist': 'Tenness...","{'song': 'Gotta Have Rain', 'artist': 'Eydie G...","{'song': 'Nothing In The World', 'artist': 'Na...","{'song': 'Baubles, Bangles And Beads', 'artist..."
2,"{'song': 'Nel Blu Dipinto Di Blu (Volare)', 'a...","{'song': 'Little Star', 'artist': 'The Elegant...","{'song': 'My True Love', 'artist': 'Jack Scott...","{'song': 'Poor Little Fool', 'artist': 'Ricky ...","{'song': 'Patricia', 'artist': 'Perez Prado An...","{'song': 'Just A Dream', 'artist': 'Jimmy Clan...","{'song': 'When', 'artist': 'Kalin Twins', 'thi...","{'song': 'Rebel-'rouser', 'artist': 'Duane Edd...","{'song': 'Fever', 'artist': 'Peggy Lee', 'this...","{'song': 'Splish Splash', 'artist': 'Bobby Dar...",...,"{'song': 'Down The Aisle Of Love', 'artist': '...","{'song': 'Return To Me', 'artist': 'Dean Marti...","{'song': 'Down In Virginia', 'artist': 'Jimmy ...","{'song': 'Fire Of Love', 'artist': 'Jody Reyno...","{'song': 'Put A Ring On My Finger', 'artist': ...","{'song': 'It's All In The Game', 'artist': 'To...","{'song': 'Ma Ma Ma Marie', 'artist': 'The Gayl...","{'song': 'Where The Blue Of The Night', 'artis...","{'song': 'Who Are They To Say', 'artist': 'The...","{'song': 'Going To Chicago Blues', 'artist': '..."
3,"{'song': 'Little Star', 'artist': 'The Elegant...","{'song': 'Nel Blu Dipinto Di Blu (Volare)', 'a...","{'song': 'Bird Dog', 'artist': 'The Everly Bro...","{'song': 'Just A Dream', 'artist': 'Jimmy Clan...","{'song': 'My True Love', 'artist': 'Jack Scott...","{'song': 'Poor Little Fool', 'artist': 'Ricky ...","{'song': 'Patricia', 'artist': 'Perez Prado An...","{'song': 'Born Too Late', 'artist': 'Poni-Tail...","{'song': 'Fever', 'artist': 'Peggy Lee', 'this...","{'song': 'When', 'artist': 'Kalin Twins', 'thi...",...,"{'song': 'Ramrod', 'artist': 'Duane Eddy His T...","{'song': 'Just Like In The Movies', 'artist': ...","{'song': 'The Purple People Eater', 'artist': ...","{'song': 'You Cheated', 'artist': 'The Shields...","{'song': 'No One Knows', 'artist': 'Dion & The...","{'song': 'Return To Me', 'artist': 'Dean Marti...","{'song': 'Little Brass Band', 'artist': 'David...","{'song': 'You're A Sweetheart', 'artist': 'Lit...","{'song': 'You Cheated', 'artist': 'The Slades'...","{'song': 'Treasure Of Your Love', 'artist': 'E..."
4,"{'song': 'Nel Blu Dipinto Di Blu (Volare)', 'a...","{'song': 'Little Star', 'artist': 'The Elegant...","{'song': 'Bird Dog', 'artist': 'The Everly Bro...","{'song': 'Just A Dream', 'artist': 'Jimmy Clan...","{'song': 'Poor Little Fool', 'artist': 'Ricky ...","{'song': 'Patricia', 'artist': 'Perez Prado An...","{'song': 'My True Love', 'artist': 'Jack Scott...","{'song': 'When', 'artist': 'Kalin Twins', 'thi...","{'song': 'Ginger Bread', 'artist': 'Frankie Av...","{'song': 'Are You Really Mine', 'artist': 'Jim...",...,"{'song': 'Hey Girl - Hey Boy', 'artist': 'Osca...","{'song': 'Endless Sleep', 'artist': 'Jody Reyn...","{'song': 'Over The Weekend', 'artist': 'The Pl...","{'song': 'Blue Ribbon Baby', 'artist': 'Tommy ...","{'song': 'Old MacDonald', 'artist': 'The Charg...","{'song': 'Week End', 'artist': 'The Kingsmen',...","{'song': 'Up Until Now', 'artist': 'Johnnie Ra...","{'song': 'La-Do-Dada', 'artist': 'Dale Hawkins...","{'song': 'Pickle Up A Doodle', 'artist': 'Tere...","{'song': 'Big Daddy', 'artist': 'Jill Corey', ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3510,"{'song': 'The Fate Of Ophelia', 'artist': 'Tay...","{'song': 'Golden', 'artist': 'HUNTR/X: EJAE, A...","{'song': 'Ordinary', 'artist': 'Alex Warren', ...","{'song': 'Opalite', 'artist': 'Taylor Swift', ...","{'song': 'Man I Need', 'artist': 'Olivia Dean'...","{'song': 'Daisies', 'artist': 'Justin Bieber',...","{'song': 'Folded', 'artist': 'Kehlani', 'this_...","{'song': 'Mutt', 'artist': 'Leon Thomas', 'thi...","{'song': 'I Got Better', 'artist': 'Morgan Wal...","{'song': 'Thriller', 'artist': 'Michael Jackso...",...,"{'song': 'I Ain't Coming Back', 'artist': 'Mor...","{'song': 'Wish', 'artist': 'Diplo Featuring Tr...","{'song': 'Come N Go', 'artist': 'Yeat', 'this_...","{'song': '3,2,1', 'artist': 'Tucker Wetmore', ...","{'song': 'I'm Not There For You', 'artist': 'j...","{'song': 'Breakin' Dishes', 'artist': 'Rihanna...","{'song': 'Shake It To The Max (Fly)', 'artist'...","{'song': 'Let Down', 'artist': 'Radiohead', 't...","{'song': '3am', 'artist': 'Loe Shimmy & Don To...","{'song': 'Nice To Each Other', 'artist': 'Oliv..."
3511,"{'song': 'The Fate Of Ophelia', 'artist': 'Tay...","{'song': 'Golden', 'artist': 'HUNTR/X: EJAE, A...","{'song': 'Ordinary', 'artist': 'Alex Warren', ...","{'song': 'Man I Need', 'artist': 'Olivia Dean'...","{'song': 'Opalite', 'artist': 'Taylor Swift', ...","{'song': 'Daisies', 'artist': 'Justin Bieber',...","{'song': 'Mutt', 'artist': 'Leon Thomas', 'thi...","{'song': 'Folded', 'artist': 'Kehlani', 'this_...","{'song': 'I Got Better', 'artist': 'Morgan Wal...","{'song': 'Back To Friends', 'artist': 'sombr',...",...,"{'song': 'Nice To Each Other', 'artist': 'Oliv...","{'song': 'Takedown', 'artist': 'JEONGYEON, JIH...","{'song': 'Amor', 'artist': 'Emmanuel Cortes', ...","{'song': 'Let Down', 'artist': 'Radiohead', 't...","{'song': '3,2,1', 'artist': 'Tucker Wetmore', ...","{'song': 'Come N Go', 'artist': 'Yeat', 'this_...","{'song': 'Pixelated Kisses', 'artist': 'Joji',...","{'song': 'Nobody's Son', 'artist': 'Sabrina Ca...","{'song': 'I Ain't Coming Back', 'artist': 'Mor...","{'song': '3am', 'artist': 'Loe Shimmy & Don To..."
3512,"{'song': 'The Fate Of Ophelia', 'artist': 'Tay...","{'song': 'Golden', 'artist': 'HUNTR/X: EJAE, A...","{'song': 'Ordinary', 'artist': 'Alex Warren', ...","{'song': 'Man I Need', 'artist': 'Olivia Dean'...","{'song': 'Opalite', 'artist': 'Taylor Swift', ...","{'song': 'Mutt', 'artist': 'Leon Thomas', 'thi...","{'song': 'Daisies', 'artist': 'Justin Bieber',...","{'song': 'All I Want For Christmas Is You', 'a...","{'song': 'Folded', 'artist': 'Kehlani', 'this_...","{'song': 'I Got Better', 'artist': 'Morgan Wal...",...,"{'song': 'When Did You Get Hot?', 'artist': 'S...","{'song': 'Sienna', 'artist': 'The Marias', 'th...","{'song': 'Camera', 'artist': 'Ed Sheeran', 'th...","{'song': 'Days Like These', 'artist': 'Luke Co...","{'song': 'Amen', 'artist': 'Shaboozey & Jelly ...","{'song': 'Baller', 'artist': 'Summer Walker, G...","{'song': 'Let Alone The One You Love', 'artist...","{'song': 'Losin' Streak', 'artist': 'Blake Rom...","{'song': 'Favorite Country Song', 'artist': 'H...","{'song': 'How Far Does A Goodbye Go', 'artist'..."
3513,"{'song': 'The Fate Of Ophelia', 'artist': 'Tay...","{'song': 'Golden', 'artist': 'HUNTR/X: EJAE, A...","{'song': 'Ordinary', 'artist': 'Alex Warren', ...","{'song': 'Man I Need', 'artist': 'Olivia Dean'...","{'song': 'All I Want For Christmas Is You', 'a...","{'song': 'Last Christmas', 'artist': 'Wham!', ...","{'song': 'Rockin' Around The Christmas Tree', ...","{'song': 'Jingle Bell Rock', 'artist': 'Bobby ...","{'song': 'Mutt', 'artist': 'Leon Thomas', 'thi...","{'song': 'Opalite', 'artist': 'Taylor Swift', ...",...,"{'song': 'As Long As You're Mine', 'artist': '...","{'song': 'How Far Does A Goodbye Go', 'artist'...","{'song': 'Safe', 'artist': 'Cardi B Featuring ...","{'song': 'The Dead Dance', 'artist': 'Lady Gag...","{'song': 'Let Alone The One You Love', 'artist...","{'song': 'When Did You Get Hot?', 'artist': 'S...","{'song': 'Sparks', 'artist': 'Coldplay', 'this...","{'song': 'Ruin The Friendship', 'artist': 'Tay...","{'song': 'What You Is', 'artist': 'YoungBoy Ne...","{'song': 'The Girl In The Bubble', 'artist': '..."
3514,"{'song': 'All I Want For Christmas Is You', 'a...","{'song': 'Last Christmas', 'artist': 'Wham!', ...","{'song': 'Rockin' Around The Christmas Tree', ...","{'song': 'Jingle Bell Rock', 'artist': 'Bobby ...","{'song': 'Golden', 'artist': 'HUNTR/X: EJAE, A...","{'song': 'The Fate Of Ophelia', 'artist': 'Tay...","{'song': 'Ordinary', 'artist': 'Alex Warren', ...","{'song': 'Santa Tell Me', 'artist': 'Ariana Gr...",{'song': 'The Christmas Song (Merry Christmas ...,{'song': 'It's The Most Wonderful Time Of The ...,...,"{'song': 'Nice To Each Other', 'artist': 'Oliv...","{'song': 'Gone Gone Gone', 'artist': 'David Gu...","{'song': 'The Dead Dance', 'artist': 'Lady Gag...","{'song': 'Went Legit', 'artist': 'G Herbo', 't...","{'song': 'Sienna', 'artist': 'The Marias', 'th...","{'song': 'For Good', 'artist': 'Cynthia Erivo ...","{'song': 'No Good Deed', 'artist': 'Cynthia Er...","{'song': 'Let Alone The One You Love', 'artist...","{'song': 'The Life Of A Showgirl', 'artist': '...","{'song': 'When Did You Get Hot?', 'artist': 'S..."

In [6]:
display(pd.json_normalize(file_new['data']))

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,"{'song': 'Poor Little Fool', 'artist': 'Ricky ...","{'song': 'Patricia', 'artist': 'Perez Prado An...","{'song': 'Splish Splash', 'artist': 'Bobby Dar...","{'song': 'Hard Headed Woman', 'artist': 'Elvis...","{'song': 'When', 'artist': 'Kalin Twins', 'thi...","{'song': 'Rebel-'rouser', 'artist': 'Duane Edd...","{'song': 'Yakety Yak', 'artist': 'The Coasters...","{'song': 'My True Love', 'artist': 'Jack Scott...","{'song': 'Willie And The Hand Jive', 'artist':...","{'song': 'Fever', 'artist': 'Peggy Lee', 'this...",...,{'song': 'The Purple People Eater Meets The Wi...,"{'song': 'Bird Dog', 'artist': 'The Everly Bro...","{'song': 'Are You Really Mine', 'artist': 'Jim...",{'song': 'She Was Only Seventeen (He Was One Y...,"{'song': 'Little Mary', 'artist': 'Fats Domino...","{'song': 'Over And Over', 'artist': 'Thurston ...","{'song': 'I Believe In You', 'artist': 'Robert...","{'song': 'Little Serenade', 'artist': 'The Ame...",{'song': 'I'll Get By (As Long As I Have You)'...,"{'song': 'Judy', 'artist': 'Frankie Vaughan', ..."
1,"{'song': 'Poor Little Fool', 'artist': 'Ricky ...","{'song': 'Nel Blu Dipinto Di Blu (Volare)', 'a...","{'song': 'Patricia', 'artist': 'Perez Prado An...","{'song': 'Splish Splash', 'artist': 'Bobby Dar...","{'song': 'When', 'artist': 'Kalin Twins', 'thi...","{'song': 'My True Love', 'artist': 'Jack Scott...","{'song': 'Hard Headed Woman', 'artist': 'Elvis...","{'song': 'Rebel-'rouser', 'artist': 'Duane Edd...","{'song': 'Just A Dream', 'artist': 'Jimmy Clan...","{'song': 'Willie And The Hand Jive', 'artist':...",...,"{'song': 'All I Have To Do Is Dream', 'artist'...","{'song': 'La Paloma', 'artist': 'Billy Vaughn ...","{'song': 'I Believe In You', 'artist': 'Robert...","{'song': 'Midnighter', 'artist': 'The Champs',...","{'song': 'Chariot Rock', 'artist': 'The Champs...","{'song': 'Down In Virginia', 'artist': 'Jimmy ...","{'song': 'Sunday Barbecue', 'artist': 'Tenness...","{'song': 'Gotta Have Rain', 'artist': 'Eydie G...","{'song': 'Nothing In The World', 'artist': 'Na...","{'song': 'Baubles, Bangles And Beads', 'artist..."
2,"{'song': 'Nel Blu Dipinto Di Blu (Volare)', 'a...","{'song': 'Little Star', 'artist': 'The Elegant...","{'song': 'My True Love', 'artist': 'Jack Scott...","{'song': 'Poor Little Fool', 'artist': 'Ricky ...","{'song': 'Patricia', 'artist': 'Perez Prado An...","{'song': 'Just A Dream', 'artist': 'Jimmy Clan...","{'song': 'When', 'artist': 'Kalin Twins', 'thi...","{'song': 'Rebel-'rouser', 'artist': 'Duane Edd...","{'song': 'Fever', 'artist': 'Peggy Lee', 'this...","{'song': 'Splish Splash', 'artist': 'Bobby Dar...",...,"{'song': 'Down The Aisle Of Love', 'artist': '...","{'song': 'Return To Me', 'artist': 'Dean Marti...","{'song': 'Down In Virginia', 'artist': 'Jimmy ...","{'song': 'Fire Of Love', 'artist': 'Jody Reyno...","{'song': 'Put A Ring On My Finger', 'artist': ...","{'song': 'It's All In The Game', 'artist': 'To...","{'song': 'Ma Ma Ma Marie', 'artist': 'The Gayl...","{'song': 'Where The Blue Of The Night', 'artis...","{'song': 'Who Are They To Say', 'artist': 'The...","{'song': 'Going To Chicago Blues', 'artist': '..."
3,"{'song': 'Little Star', 'artist': 'The Elegant...","{'song': 'Nel Blu Dipinto Di Blu (Volare)', 'a...","{'song': 'Bird Dog', 'artist': 'The Everly Bro...","{'song': 'Just A Dream', 'artist': 'Jimmy Clan...","{'song': 'My True Love', 'artist': 'Jack Scott...","{'song': 'Poor Little Fool', 'artist': 'Ricky ...","{'song': 'Patricia', 'artist': 'Perez Prado An...","{'song': 'Born Too Late', 'artist': 'Poni-Tail...","{'song': 'Fever', 'artist': 'Peggy Lee', 'this...","{'song': 'When', 'artist': 'Kalin Twins', 'thi...",...,"{'song': 'Ramrod', 'artist': 'Duane Eddy His T...","{'song': 'Just Like In The Movies', 'artist': ...","{'song': 'The Purple People Eater', 'artist': ...","{'song': 'You Cheated', 'artist': 'The Shields...","{'song': 'No One Knows', 'artist': 'Dion & The...","{'song': 'Return To Me', 'artist': 'Dean Marti...","{'song': 'Little Brass Band', 'artist': 'David...","{'song': 'You're A Sweetheart', 'artist': 'Lit...","{'song': 'You Cheated', 'artist': 'The Slades'...","{'song': 'Treasure Of Your Love', 'artist': 'E..."
4,"{'song': 'Nel Blu Dipinto Di Blu (Volare)', 'a...","{'song': 'Little Star', 'artist': 'The Elegant...","{'song': 'Bird Dog', 'artist': 'The Everly Bro...","{'song': 'Just A Dream', 'artist': 'Jimmy Clan...","{'song': 'Poor Little Fool', 'artist': 'Ricky ...","{'song': 'Patricia', 'artist': 'Perez Prado An...","{'song': 'My True Love', 'artist': 'Jack Scott...","{'song': 'When', 'artist': 'Kalin Twins', 'thi...","{'song': 'Ginger Bread', 'artist': 'Frankie Av...","{'song': 'Are You Really Mine', 'artist': 'Jim...",...,"{'song': 'Hey Girl - Hey Boy', 'artist': 'Osca...","{'song': 'Endless Sleep', 'artist': 'Jody Reyn...","{'song': 'Over The Weekend', 'artist': 'The Pl...","{'song': 'Blue Ribbon Baby', 'artist': 'Tommy ...","{'song': 'Old MacDonald', 'artist': 'The Charg...","{'song': 'Week End', 'artist': 'The Kingsmen',...","{'song': 'Up Until Now', 'artist': 'Johnnie Ra...","{'song': 'La-Do-Dada', 'artist': 'Dale Hawkins...","{'song': 'Pickle Up A Doodle', 'artist': 'Tere...","{'song': 'Big Daddy', 'artist': 'Jill Corey', ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3510,"{'song': 'The Fate Of Ophelia', 'artist': 'Tay...","{'song': 'Golden', 'artist': 'HUNTR/X: EJAE, A...","{'song': 'Ordinary', 'artist': 'Alex Warren', ...","{'song': 'Opalite', 'artist': 'Taylor Swift', ...","{'song': 'Man I Need', 'artist': 'Olivia Dean'...","{'song': 'Daisies', 'artist': 'Justin Bieber',...","{'song': 'Folded', 'artist': 'Kehlani', 'this_...","{'song': 'Mutt', 'artist': 'Leon Thomas', 'thi...","{'song': 'I Got Better', 'artist': 'Morgan Wal...","{'song': 'Thriller', 'artist': 'Michael Jackso...",...,"{'song': 'I Ain't Coming Back', 'artist': 'Mor...","{'song': 'Wish', 'artist': 'Diplo Featuring Tr...","{'song': 'Come N Go', 'artist': 'Yeat', 'this_...","{'song': '3,2,1', 'artist': 'Tucker Wetmore', ...","{'song': 'I'm Not There For You', 'artist': 'j...","{'song': 'Breakin' Dishes', 'artist': 'Rihanna...","{'song': 'Shake It To The Max (Fly)', 'artist'...","{'song': 'Let Down', 'artist': 'Radiohead', 't...","{'song': '3am', 'artist': 'Loe Shimmy & Don To...","{'song': 'Nice To Each Other', 'artist': 'Oliv..."
3511,"{'song': 'The Fate Of Ophelia', 'artist': 'Tay...","{'song': 'Golden', 'artist': 'HUNTR/X: EJAE, A...","{'song': 'Ordinary', 'artist': 'Alex Warren', ...","{'song': 'Man I Need', 'artist': 'Olivia Dean'...","{'song': 'Opalite', 'artist': 'Taylor Swift', ...","{'song': 'Daisies', 'artist': 'Justin Bieber',...","{'song': 'Mutt', 'artist': 'Leon Thomas', 'thi...","{'song': 'Folded', 'artist': 'Kehlani', 'this_...","{'song': 'I Got Better', 'artist': 'Morgan Wal...","{'song': 'Back To Friends', 'artist': 'sombr',...",...,"{'song': 'Nice To Each Other', 'artist': 'Oliv...","{'song': 'Takedown', 'artist': 'JEONGYEON, JIH...","{'song': 'Amor', 'artist': 'Emmanuel Cortes', ...","{'song': 'Let Down', 'artist': 'Radiohead', 't...","{'song': '3,2,1', 'artist': 'Tucker Wetmore', ...","{'song': 'Come N Go', 'artist': 'Yeat', 'this_...","{'song': 'Pixelated Kisses', 'artist': 'Joji',...","{'song': 'Nobody's Son', 'artist': 'Sabrina Ca...","{'song': 'I Ain't Coming Back', 'artist': 'Mor...","{'song': '3am', 'artist': 'Loe Shimmy & Don To..."
3512,"{'song': 'The Fate Of Ophelia', 'artist': 'Tay...","{'song': 'Golden', 'artist': 'HUNTR/X: EJAE, A...","{'song': 'Ordinary', 'artist': 'Alex Warren', ...","{'song': 'Man I Need', 'artist': 'Olivia Dean'...","{'song': 'Opalite', 'artist': 'Taylor Swift', ...","{'song': 'Mutt', 'artist': 'Leon Thomas', 'thi...","{'song': 'Daisies', 'artist': 'Justin Bieber',...","{'song': 'All I Want For Christmas Is You', 'a...","{'song': 'Folded', 'artist': 'Kehlani', 'this_...","{'song': 'I Got Better', 'artist': 'Morgan Wal...",...,"{'song': 'When Did You Get Hot?', 'artist': 'S...","{'song': 'Sienna', 'artist': 'The Marias', 'th...","{'song': 'Camera', 'artist': 'Ed Sheeran', 'th...","{'song': 'Days Like These', 'artist': 'Luke Co...","{'song': 'Amen', 'artist': 'Shaboozey & Jelly ...","{'song': 'Baller', 'artist': 'Summer Walker, G...","{'song': 'Let Alone The One You Love', 'artist...","{'song': 'Losin' Streak', 'artist': 'Blake Rom...","{'song': 'Favorite Country Song', 'artist': 'H...","{'song': 'How Far Does A Goodbye Go', 'artist'..."
3513,"{'song': 'The Fate Of Ophelia', 'artist': 'Tay...","{'song': 'Golden', 'artist': 'HUNTR/X: EJAE, A...","{'song': 'Ordinary', 'artist': 'Alex Warren', ...","{'song': 'Man I Need', 'artist': 'Olivia Dean'...","{'song': 'All I Want For Christmas Is You', 'a...","{'song': 'Last Christmas', 'artist': 'Wham!', ...","{'song': 'Rockin' Around The Christmas Tree', ...","{'song': 'Jingle Bell Rock', 'artist': 'Bobby ...","{'song': 'Mutt', 'artist': 'Leon Thomas', 'thi...","{'song': 'Opalite', 'artist': 'Taylor Swift', ...",...,"{'song': 'As Long As You're Mine', 'artist': '...","{'song': 'How Far Does A Goodbye Go', 'artist'...","{'song': 'Safe', 'artist': 'Cardi B Featuring ...","{'song': 'The Dead Dance', 'artist': 'Lady Gag...","{'song': 'Let Alone The One You Love', 'artist...","{'song': 'When Did You Get Hot?', 'artist': 'S...","{'song': 'Sparks', 'artist': 'Coldplay', 'this...","{'song': 'Ruin The Friendship', 'artist': 'Tay...","{'song': 'What You Is', 'artist': 'YoungBoy Ne...","{'song': 'The Girl In The Bubble', 'artist': '..."
3514,"{'song': 'All I Want For Christmas Is You', 'a...","{'song': 'Last Christmas', 'artist': 'Wham!', ...","{'song': 'Rockin' Around The Christmas Tree', ...","{'song': 'Jingle Bell Rock', 'artist': 'Bobby ...","{'song': 'Golden', 'artist': 'HUNTR/X: EJAE, A...","{'song': 'The Fate Of Ophelia', 'artist': 'Tay...","{'song': 'Ordinary', 'artist': 'Alex Warren', ...","{'song': 'Santa Tell Me', 'artist': 'Ariana Gr...",{'song': 'The Christmas Song (Merry Christmas ...,{'song': 'It's The Most Wonderful Time Of The ...,...,"{'song': 'Nice To Each Other', 'artist': 'Oliv...","{'song': 'Gone Gone Gone', 'artist': 'David Gu...","{'song': 'The Dead Dance', 'artist': 'Lady Gag...","{'song': 'Went Legit', 'artist': 'G Herbo', 't...","{'song': 'Sienna', 'artist': 'The Marias', 'th...","{'song': 'For Good', 'artist': 'Cynthia Erivo ...","{'song': 'No Good Deed', 'artist': 'Cynthia Er...","{'song': 'Let Alone The One You Love', 'artist...","{'song': 'The Life Of A Showgirl', 'artist': '...","{'song': 'When Did You Get Hot?', 'artist': 'S..."

In [7]:
new_dataset = pd.json_normalize(pd.melt(pd.json_normalize(file_new.data).transpose()).value)

In [8]:
new_dataset['date'] = new_dataset['date'][0]
k = 0
for i in file_new['date']:
    for j in range(0,100):
        new_dataset['date'][k] = i
        k = k+1

KeyError: 'date'

In [ ]:
new_dataset['date'] = 0
new_dataset['date'][0] = 1

In [ ]:
new_dataset['date'] = pd.to_datetime(new_dataset['date']).dt.date

In [ ]:
new_dataset.head(5)

In [ ]:
new_dataset = new_dataset.iloc[:, [6,0,1,2,3,4,5]]
new_dataset

In [ ]:

table = pa.Table.from_pandas(new_dataset)
pq.write_table(table, 'raw/billboard/billboard_100_OAT.parquet')

In [ ]:
new_dataset.to_json('raw/billboard/billboard_100_OAT.json')

In [ ]:
new_dataset.to_csv('raw/billboard/billboard_100_OAT.csv', index=False)